import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  CircleEllipsis,
  CircleHelp,
  Coffee,
  Coins,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Lightbulb,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  TrendingUp,
  Undo2,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  wallet: Wallet,
  banknote: Banknote,
  "credit-card": CreditCard,
  coins: Coins,
  "hand-coins": HandCoins,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  briefcase: Briefcase,
  laptop: Laptop,
  store: Store,
  "trending-up": TrendingUp,
  gift: Gift,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  car: Car,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  receipt: Receipt,
  zap: Zap,
  lightbulb: Lightbulb,
  wifi: Wifi,
  phone: Phone,
  smartphone: Smartphone,
  home: Home,
  wrench: Wrench,
  "heart-pulse": HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  film: Film,
  "gamepad-2": Gamepad2,
  shirt: Shirt,
  sparkles: Sparkles,
  baby: Baby,
  "paw-print": PawPrint,
  users: Users,
  undo: Undo2,
  "circle-ellipsis": CircleEllipsis,
};

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? CircleHelp;
}
